languageCode = "en-us"
theme = "kross-hugo"
summaryLength = "10"
title = "Climate Refugee Stories"
baseURL = "https://www.climaterefugeestories.com"

[params]
logo = ""
theme_color = "#054ca7"
baidu_site_verification = ""
baidu_analytics_id = ""
google_analytics_id = ""
email = "climaterefugeestories@gmail.com"
description = "Climate Migration Stories Official Website"
home = "Home"

[params.contact]
enable = true
form_action = "https://formspree.io/f/mdobaknv"

[params.plugins]

[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"

[[params.plugins.css]]
link = "plugins/slick/slick.css"

[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"

[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"

[[params.plugins.js]]
link = "plugins/slick/slick.min.js"

[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"

[[params.plugins.js]]
link = "plugins/google-map/map.js"

[params.cookies]
enable = true
expire_days = 7

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags", "description", "summary"]

[params.preloader]
enable = true
preloader = "images/preloader.gif"

[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=&#038;types=(cities)&#038;libraries=places&#038;language=en"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

[outputs]
home = ["HTML", "RSS", "Algolia"]

[outputFormats]

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[menu]

[[menu.main]]
URL = "about"
name = "About"
weight = 1
identifier = "about"

[[menu.main]]
URL = "about"
name = "About Us"
weight = 1
parent = "about"

[[menu.main]]
name = "Our Team"
URL = "about/#our-team"
parent = "about"
weight = 2

[[menu.main]]
name = "Our Partners"
URL = "about/#partners"
parent = "about"
weight = 3

[[menu.main]]
name = "CRS News"
URL = "about/#crs-news"
parent = "about"
weight = 4

[[menu.main]]
URL = "stories"
name = "Stories"
weight = 2

[[menu.main]]
URL = "archive"
name = "Archive"
weight = 3

[[menu.main]]
name = "Resources"
weight = 4
identifier = "resources"

[[menu.main]]
name = "All Resources"
URL = "resources"
parent = "resources"

[[menu.main]]
name = "Climate Migration Syllabus"
URL = "resources/#climate-migration-syllabus"
parent = "resources"

[[menu.main]]
name = "K-12 Curriculum"
URL = "resources/#k-12-curriculum"
parent = "resources"

[[menu.main]]
name = "Take Action"
URL = "resources/#take-action"
parent = "resources"

[[menu.main]]
URL = "contact"
name = "Contact"
weight = 5