# default configuration
baseURL = "https://www.climaterefugeestories.com/"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "Climate Refugee Stories"

# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"


# js plugin
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"


# menu
[[menu.main]]
URL = "about"
name = "About"
weight = 1
identifier = "about"

[[menu.main]]
URL = "about"
name = "About Us"
weight = 1
parent = "about"

[[menu.main]]
name = "Our Partners"
URL = "about/#partners"
parent = "about"
weight = 2

[[menu.main]]
name = "Our Team"
URL = "about/#our-team"
parent = "about"
weight = 3

[[menu.main]]
name = "CRS News"
URL = "about/#crs-news"
parent = "about"
weight = 4

[[menu.main]]
URL = "stories"
name = "Stories"
weight = 2

[[menu.main]]
URL = "archive"
name = "Archive"
weight = 3

[[menu.main]]
name = "Resources"
weight = 4
identifier = "resources"

[[menu.main]]
name = "All Resources"
URL = "resources"
parent = "resources"

[[menu.main]]
name = "Climate Migration Syllabus"
URL = "resources/#climate-migration-syllabus"
parent = "resources"

[[menu.main]]
name = "K-12 Curriculum"
URL = "resources/#k-12-curriculum"
parent = "resources"

[[menu.main]]
name = "Take Action"
URL = "resources/#take-action"
parent = "resources"

[[menu.main]]
URL = "contact"
name = "Contact"
weight = 5


# default parameters
[params]
home = "Home"
logo = ""
# theme color
theme_color = "#054ca7"
# contact info
# phone = "+880 2544 658 256"
email = "climaterefugeestories@gmail.com"
# address = "125/A, CA Commercial Area, California, USA"
# meta description
# author = "Johnathan Smith"
description = "Climate Migration Stories Official Website"
# google analytics
google_analytics_id = "" # Your ID
# baidu site verification
baidu_site_verification = "" #Your verification code
# baidu analytics
baidu_analytics_id = "" #Your ID


# preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use png, jpg, svg or gif format

# contact
[params.contact]
enable = true
form_action = "https://formspree.io/f/mdobaknv"

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=&#038;types=(cities)&#038;libraries=places&#038;language=en"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

# cookies
[params.cookies]
enable = true
expire_days = 7

# social site
[[params.social]]
icon = "ti-facebook"
URL = "https://www.facebook.com/climaterefugeestories/"

[[params.social]]
icon = "ti-twitter-alt"
URL = "https://twitter.com/ClimRefStories"

[[params.social]]
icon = "ti-instagram"
URL = "https://www.instagram.com/climaterefugeestories/"

#[[params.social]]
#icon = "ti-dribbble"
#URL = "#"

# Algolia output config
[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags", "description", "summary"]

[outputs]
home = ["HTML", "RSS", "Algolia"]
