collapsed_defaults: &collapsed_defaults
  collapsed: true
object_defaults: &object_defaults
  widget: "object"
  <<: *collapsed_defaults
list_defaults: &list_defaults
  widget: "list"
  <<: *collapsed_defaults
markdown_defaults: &markdown_defaults
  widget: "markdown"
  sanitize_preview: true


backend:
  name: github
  repo:  Climate-Refugee-Stories/crs-website  # Path to your Github repository
  # branch: master # Branch to update
  branch: feat/Content-Management-System

# use google drive not this upload
media_folder: 'N/a'
publish_mode: editorial_workflow

collections:
  - name: "list_files"
    label: "Main Pages"
    files:
      - name: homepage
        label: "Homepage"
        file: content/_index.md
        fields:
          - name: banner
            label: Banner Section
            summary: First section on homepage
            <<: *object_defaults
            fields:
              - name: "title"
                label: Title Section
                <<: *markdown_defaults
              - name: background_img
                label: main background image
                widget: string
              - name: logo
                label: logo on top of background image
                widget: string

          - name: about
            label: About Section
            summary: About text + button below hero section
            <<: *object_defaults
            fields:
              - &md_content
                name: content
                label: about text
                <<: *markdown_defaults
              - &button_defaults
                name: button
                label: button
                summary: button for about text
                <<: *object_defaults
                fields:
                  - name: enable
                    label: Enabled?
                    widget: boolean
                  - &link_defaults
                    name: URL
                    label: Link for navigation
                    widget: string
                  - name: label
                    label: Text for button
                    widget: string

          - name: stories
            label: stories section
            summary: Stories section + map
            <<: *object_defaults
            fields:
              - &title_defaults
                name: title
                label: Stories section title
                widget: string
              - name: map
                label: Map url (including https)
                widget: string
              - <<: *link_defaults
                label: url to link to stories page

          - name: archive
            label: Archive
            summary: Archive section options
            <<: *object_defaults
            fields:
              - <<: *title_defaults
                label: Archive section title
              - name: item_show
                label: Archive articles to show
                widget: number
                value_type: int
                min: 0
                max: 10

          - name: resources
            label: resources
            summary: Resources section
            <<: *object_defaults
            fields:
              - <<: *title_defaults
                label: Resources section title
              - <<: *button_defaults
                summary: button for resources text
              - name: item
                label: items
                <<: *list_defaults
                max: 3
                allow_add: false
                summary: More info item
                fields:
                  - <<: *title_defaults
                    label: Item title
                  - &icon_defaults
                    name: icon
                    label: Font Awesome Icon string
                    widget: string
                  - <<: *md_content
                    label: Text for item
                  - name: highlighted
                    label: Highlight text (with blue)?
                    widget: boolean
                    default: false
      - name: about
        label: "About"
        file: content/about/_index.md
        fields:
          - &metadata_defaults
            name: description
            label: metadata for page
            widget: text
          - &draft_defaults
            name: draft
            label: Draft?
            widget: boolean
          - <<: *title_defaults
            label: Title at top of page
          - &content_defaults
            name: body
            label: Content
            <<: *markdown_defaults
          - name: partners
            label: Partners
            summary: All partner information
            <<: *object_defaults
            fields:
              - name: enable
                label: Enable on homepage?
                widget: boolean
              - name: about
                label: Intro partner text
                <<: *markdown_defaults
              - name: item
                label: Partners
                summary: Partner logo & link
                <<: *list_defaults
                fields:
                  - name: logo
                    label: Partner Logo
                    widget: string
                  - name: link
                    label: Link to partner's website
                    widget: string
      - name: crs_news
        label: "CRS News"
        file: content/about/crs-news.md
        fields:
          - <<: *title_defaults
            label: CRS News section title
          - *draft_defaults
          - name: description
            label: section intro
            <<: *markdown_defaults
          - *content_defaults
          - <<: *button_defaults
            label: More CRS News

  - name: stories
    label: Stories
    folder: content/stories
    create: true
    filter: 
      field: visibleInCMS
      value: true
    fields:
      - label: Title
        name: title
        widget: string
        required: true
      - label: Creation Date
        name: date
        widget: datetime
        date_format: DD/MM/YYYY
        time_format: HH:mm:ssZ
      - *draft_defaults
      - label: Cover Image
        name: image
        widget: string
      - label: Cover Thumbnail
        name: thumbnail
        widget: string
      - label: Image Caption
        name: image_caption
        <<: *markdown_defaults
      - *content_defaults
      - name: visibleInCMS
        widget: hidden
        default: true
