object_defaults: &object_defaults
  widget: "object"
  collapsed: true
markdown_defaults: &markdown_defaults
  widget: "markdown"
  sanitize_preview: true


backend:
  name: github
  repo:  Climate-Refugee-Stories/crs-website  # Path to your Github repository
  # branch: master # Branch to update
  branch: feat/Content-Management-System

# use google drive not this upload
media_folder: 'N/a'
publish_mode: editorial_workflow

collections:
  - name: "list_files"
    label: "Main Pages"
    files:
      - name: homepage
        label: "Homepage"
        file: content/_index.md
        fields:
          - name: banner
            label: Banner Section
            summary: First section on homepage
            <<: *object_defaults
            fields:
              - name: "title"
                label: Title Section
                <<: *markdown_defaults
              - name: background_img
                label: main background image
                widget: string
              - name: logo
                label: logo on top of background image
                widget: string
          - name: about
            label: About Section
            summary: About text + button below hero section
            <<: *object_defaults
            fields:
              - name: content
                label: about text
                <<: *markdown_defaults
              - name: button
                label: button
                summary: button for about text
                <<: *object_defaults
                fields: &button_defaults
                  - name: enable
                    label: Enabled?
                    widget: boolean
                  - name: URL
                    label: Link for navigation
                    widget: string
                  - name: label
                    label: Text for button
                    widget: string


  - name: stories
    label: Stories
    folder: content/stories
    create: true
    filter: 
      field: visibleInCMS
      value: true
    fields:
      - label: Title
        name: title
        widget: string
        required: true
      - label: Creation Date
        name: date
        widget: datetime
        date_format: DD/MM/YYYY
        time_format: HH:mm:ssZ
      - label: Draft
        name: draft
        widget: boolean
        default: true
      - label: Cover Image
        name: image
        widget: string
      - label: Cover Thumbnail
        name: thumbnail
        widget: string
      - label: Image Caption
        name: image_caption
        <<: *markdown_defaults
      - label: Body
        name: body
        <<: *markdown_defaults
      - name: visibleInCMS
        widget: hidden
        default: true
