---
name: Deploy Website

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  prod_prep:
    name: Actions creating the Archive data file (archive_data.json)
    runs-on: ubuntu-latest
    needs: prod
    container:
      image: docker.io/python:3-slim

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        # with:
        #   ref: "gh-pages"

      - name: Install pipenv
        run: pip install pipenv

      - uses: actions/setup-python@v3
        with:
          python-version: "3.x"
          cache: "pipenv"

      - name: installing pipenv packages
        run: pushd .github/repo_ci-cd/deployment/ && pipenv sync && popd

      - name: Update Archive data
        run: pushd .github/repo_ci-cd/deployment/ && pipenv run ./csv_to_json.py > "${GITHUB_WORKSPACE}/data/archive_data.json" && popd

      - name: uploading archive data
        uses: actions/upload-artifact@v3
        with:
          name: archive-data
          path: data/archive_data.json

  prod:
    name: Deploy to prod
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/pages/hugo/hugo_extended:latest

    steps:
      - name: Prep env
        run: |
          set -ex
          apk add --update --no-cache openssl git bash &&
          rm -rf /var/cache/apk/*

      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: downloading archive data
        uses: actions/download-artifact@v3
        with:
          name: archive-data
          path: data/archive_data.json

      - name: Deploy to Github Pages
        run: bash .github/repo_ci-cd/deployment/deploy.sh
        env:
          GITHUBTOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARGZ: --gc --minify --cleanDestinationDir -e prod
          GH_PAGES: gh-pages
          #DEBUG: 'true'

        # uses: chabad360/hugo-gh-pages@v2
        # with:
        #   githubToken: ${{ secrets.GITHUB_TOKEN }}
        # env:
        #   HUGO_ARGS: --gc --minify --cleanDestinationDir
        # CNAME: <domain>

      - name: uploading algolia data
        uses: actions/upload-artifact@v3
        with:
          name: algolia-data
          path: /tmp/gh-pages/algolia.json

  auto_actions:
    name: Actions to update Algolia after site's been deployed
    runs-on: ubuntu-latest
    needs: prod
    container:
      image: docker.io/python:3-slim

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install pipenv
        run: pip install pipenv

      - uses: actions/setup-python@v3
        with:
          python-version: "3.x"
          cache: "pipenv"

      - name: installing pipenv packages
        run: pushd .github/repo_ci-cd/deployment/ && pipenv sync && popd

      - name: downloading algolia data
        uses: actions/download-artifact@v3
        with:
          name: algolia-data

      - name: Update Algolia index
        run: cd .github/repo_ci-cd/deployment/ && pipenv run ./algolia.py
