---
name: Deploy Website

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  prod:
    name: Deploy to prod
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/pages/hugo/hugo_extended:latest

    steps:
      - name: Prep env
        run: |
          set -ex
          apk add --update --no-cache openssl git bash &&
          rm -rf /var/cache/apk/*

      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Deploy to Github Pages
        run: bash .github/repo_ci-cd/deployment/deploy.sh
        env:
          GITHUBTOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARGZ: --gc --minify --cleanDestinationDir -e prod
          GH_PAGES: gh-pages
          #DEBUG: 'true'

        # uses: chabad360/hugo-gh-pages@v2
        # with:
        #   githubToken: ${{ secrets.GITHUB_TOKEN }}
        # env:
        #   HUGO_ARGS: --gc --minify --cleanDestinationDir
        # CNAME: <domain>

  auto_actions:
    name: Actions around the prod deployment
    runs-on: ubuntu-latest
    needs: prod
    container:
      image: docker.io/python:3-slim

    steps:
      # - name: Prep env
      #   run: |
      #     set -ex
      #     apk add --update --no-cache openssl git bash &&
      #     rm -rf /var/cache/apk/*

      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: "gh-pages"

      - name: Install pipenv
        run: pip install pipenv

      - uses: actions/setup-python@v3
        with:
          python-version: "3.x"
          cache: "pipenv"

      - run: cd .github/repo_ci-cd/deployment/ && pipenv install

      - name: Update Algolia index
        run: cd .github/repo_ci-cd/deployment/ && pipenv run ./csv_to_json.py > ../../../data/archive_data.json

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Adding archive data to gh-pages branch

      - name: Update Algolia index
        run: cd .github/repo_ci-cd/deployment/ && pipenv run ./algolia.py
